version: '3.6'

services:
  ## Start Grafana service
  ia_grafana:
    depends_on:
      - ia_common
    build:
      context: $PWD/../Grafana
      dockerfile: $PWD/../Grafana/Dockerfile
      args:
          EIS_VERSION: ${EIS_VERSION}
          GRAFANA_VERSION: ${GRAFANA_VERSION}
          EIS_UID: ${EIS_UID}
    image: ${DOCKER_REGISTRY}ia_grafana:${EIS_VERSION}
    container_name: ia_grafana
    hostname: ia_grafana
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "Grafana"
      InfluxDbAppName: "InfluxDBConnector"
      CertType: "pem"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_PREFIX: ${ETCD_PREFIX}
    secrets:
      - ca_etcd
      - etcd_Grafana_cert
      - etcd_Grafana_key
      - etcd_InfluxDBConnector_cert
      - etcd_InfluxDBConnector_key

secrets:
  etcd_Grafana_cert:
    file: provision/Certificates/Grafana/Grafana_client_certificate.pem
  etcd_Grafana_key:
    file: provision/Certificates/Grafana/Grafana_client_key.pem
  etcd_InfluxDBConnector_cert:
    file: provision/Certificates/InfluxDBConnector/InfluxDBConnector_client_certificate.pem
  etcd_InfluxDBConnector_key:
    file: provision/Certificates/InfluxDBConnector/InfluxDBConnector_client_key.pem
