# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Start Grafana service
  ia_grafana:
    depends_on:
      - ia_common
    build:
      context: $PWD/../Grafana
      dockerfile: $PWD/../Grafana/Dockerfile
      args:
          EIS_VERSION: ${EIS_VERSION}
          GRAFANA_VERSION: ${GRAFANA_VERSION}
          EIS_UID: ${EIS_UID}
          DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: ${DOCKER_REGISTRY}ia_grafana:${EIS_VERSION}
    container_name: ia_grafana
    hostname: ia_grafana
    network_mode: host
    read_only: true
    restart: unless-stopped
    ipc: "none"
    environment:
      AppName: "Grafana"
      CertType: "pem"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_PREFIX: ${ETCD_PREFIX}
      INFLUX_SERVER: '127.0.0.1'
      GRAFANA_SERVER: '0.0.0.0'
    user: ${EIS_UID}
    volumes:
       - "vol_temp_grafana:/tmp"
    ports:
      - "$GRAFANA_PORT:$GRAFANA_PORT"
    secrets:
      - ca_etcd
      - etcd_Grafana_cert
      - etcd_Grafana_key
      - etcd_InfluxDBConnector_cert
      - etcd_InfluxDBConnector_key

volumes:
  vol_temp_grafana:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  etcd_Grafana_cert:
    file: provision/Certificates/Grafana/Grafana_client_certificate.pem
  etcd_Grafana_key:
    file: provision/Certificates/Grafana/Grafana_client_key.pem
  etcd_InfluxDBConnector_cert:
    file: provision/Certificates/InfluxDBConnector/InfluxDBConnector_client_certificate.pem
  etcd_InfluxDBConnector_key:
    file: provision/Certificates/InfluxDBConnector/InfluxDBConnector_client_key.pem
